name = "hand-drawn-gallery"
compatibility_date = "2024-09-29"
pages_build_output_dir = "./dist/cloudflare"
compatibility_flags = [ "nodejs_compat_v2" ]
#workers_dev = true

[[kv_namespaces]]
binding = "DB"
id = "86e1f5730885467db55d774daf98b3d4"

[vars]
IMGBB_API_KEY = ""
GEMINI_API_KEY = ""
